[package]
name = "ratmac"
version = "0.1.0"
edition = "2021"

[lib]
name = "ratmac"
path = "src/lib.rs"

[workspace]
members = ["test/qa"]
resolver = "2"

[features]
test-fault-injection = []

[dependencies]
toml = "0.8"
serde = { version = "1", features = ["derive"] }
sha2 = "0.10"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = ["Win32_Storage_FileSystem"] }
