use std::path::{Path, PathBuf};
use std::process::Command;

fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("QA crate must live below the workspace root")
        .to_path_buf()
}

fn cargo_metadata(root: &Path) -> String {
    let output = Command::new("cargo")
        .args([
            "metadata",
            "--no-deps",
            "--format-version",
            "1",
            "--locked",
            "--manifest-path",
        ])
        .arg(root.join("Cargo.toml"))
        .output()
        .expect("cargo metadata must be executable");
    assert!(
        output.status.success(),
        "cargo metadata failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    String::from_utf8(output.stdout).expect("cargo metadata must be UTF-8")
}

fn git_files(root: &Path, path: &str) -> String {
    let output = Command::new("git")
        .args(["ls-files", "--", path])
        .current_dir(root)
        .output()
        .expect("git must be executable");
    assert!(
        output.status.success(),
        "git ls-files failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    String::from_utf8(output.stdout).expect("git output must be UTF-8")
}

#[test]
fn generated_metadata_is_canonical() {
    let root = workspace_root();
    let metadata = cargo_metadata(&root);

    assert!(metadata.contains(r#""name":"ratmac""#));
    assert!(metadata.contains(r#""name":"ratmac-qa""#));
    assert!(metadata.contains("src/bin/rtm.rs") || metadata.contains(r#"src\\bin\\rtm.rs"#));
    assert!(!metadata.contains(r#""name":"arca-scheduler""#));
    assert!(!metadata.contains(r#""name":"arca-scheduler-qa""#));
    assert!(!metadata.contains(r#""name":"schd""#));

    let lock =
        std::fs::read_to_string(root.join("Cargo.lock")).expect("Cargo.lock must be readable");
    assert!(lock.starts_with("# This file is automatically @generated by Cargo."));
    assert!(lock.contains("name = \"ratmac\""));
    assert!(lock.contains("name = \"ratmac-qa\""));
    assert!(lock.contains("\"ratmac\""));
    assert!(!lock.contains("name = \"arca-scheduler\""));
    assert!(!lock.contains("name = \"arca-scheduler-qa\""));
    assert!(!lock.contains("name = \"schd\""));

    let ignore =
        std::fs::read_to_string(root.join(".gitignore")).expect(".gitignore must be readable");
    assert!(ignore.lines().any(|line| line.trim() == "target"));
    assert!(git_files(&root, "target").trim().is_empty());
}
